In [1]:
import cobra
from dGbyG.api import predict_transformed_dG_prime_for_GEM

In [2]:
compartment_conditions = {
    "Cytosol": {"pH": 7.2, "I": 0.25, "e_potential": 0.000},
    "Extracellular": {"pH": 7.4, "I": 0.25, "e_potential": 0.030},
    "Nucleus": {"pH": 7.2, "I": 0.25, "e_potential": 0.000},
    "Endoplasmic reticulum": {"pH": 7.2, "I": 0.25, "e_potential": 0.000},
    "Golgi apparatus": {"pH": 6.3, "I": 0.25, "e_potential": 0.000},
    "Lysosome": {"pH": 5.5, "I": 0.25, "e_potential": 0.019},
    "Mitochondria": {"pH": 8.0, "I": 0.25, "e_potential": -0.155},
    "Inner mitochondria": {"pH": 7.0, "I": 0.25, "e_potential": 0.000},
    "Peroxisome": {"pH": 7.0, "I": 0.25, "e_potential": 0.012}
}

In [3]:
gem_path = './Mouse-GEM.xml'
gem = cobra.io.read_sbml_model(gem_path)

https://identifiers.org/taxonomy/ does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id

In [4]:
x = set()
for met in gem.metabolites:
    for cid_type, cid in met.annotation.items():
        x.add(cid_type)
print('CID types: ',x)

CID types:  {'kegg.compound', 'metanetx.chemical', 'lipidmaps', 'pubchem.compound', 'chebi', 'bigg.metabolite', 'sbo', 'hmdb', 'inchi', 'vmhmetabolite'}

In [8]:
Met_df, Rxn_df = predict_transformed_dG_prime_for_GEM(gem, compartment_conditions=compartment_conditions, ignore_met_id_types=['name', 'inchi_key'])

Processing metabolites: 100%|██████████| 8454/8454 [00:53<00:00, 159.12it/s]

✅ All molecules exist in the pKa database — skipping prediction.

Predicting transformed standard Gibbs free energy for metabolites: 100%|██████████| 8454/8454 [24:14<00:00,  5.81it/s]
Predicting transformed standard Gibbs free energy for reactions: 100%|██████████| 12987/12987 [01:26<00:00, 149.85it/s]

In [9]:
Met_df.head()

,bigg.metabolite,chebi,kegg.compound,metanetx.chemical,hmdb,pubchem.compound,lipidmaps,inchi
MAM00001c,"(718.0063760200995, 9.5092134475708)","(718.0063760200995, 9.50921630859375)","(718.0063760200995, 9.50921630859375)","(nan, nan)",NaN,NaN,NaN,NaN
MAM00001e,"(736.2622027237875, 9.509214401245117)","(736.2622027237875, 9.50921630859375)","(736.2622027237875, 9.50921630859375)","(nan, nan)",NaN,NaN,NaN,NaN
MAM00002c,"(nan, nan)","(850.2859780708899, 12.084856986999512)","(850.2859780708899, 12.084856986999512)","(nan, nan)","(850.2859780708899, 12.084856033325195)","(850.2859780708899, 12.08484935760498)",NaN,NaN
MAM00002e,"(nan, nan)","(868.5418047745924, 12.084853172302246)","(868.5418047745924, 12.084856986999512)","(nan, nan)","(868.5418047745924, 12.084855079650879)","(868.5418047745924, 12.084856986999512)",NaN,NaN
MAM00003c,NaN,"(1123.998093883676, 4.011264324188232)",NaN,"(nan, nan)",NaN,NaN,"(1123.998093883676, 4.011266708374023)",NaN

In [10]:
Rxn_df.head(5)

          dGr_prime  SD of dGr_prime
MAR03905  20.031905         0.855806
MAR03907  20.031880         0.855823
MAR04097  -5.813766         0.424463
MAR04099  -5.731635         0.424455
MAR04108 -21.468129         3.954923